config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'registrations' }  
  root 'posts#index'  
  resources :posts do  
    resources :comments
  end  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  has_attached_file :image, styles: { :medium => "420x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/post.rb
class Post < ActiveRecord::Base 

  belongs_to :user  
  validates :user_id, presence: true 
  validates :caption, presence: true, unless: ->(post){image.present?}

  has_attached_file :image, styles: { :medium => "642x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
   
  has_many :comments, dependent: :destroy 

end  

app/models/user.rb
class User < ActiveRecord::Base 
	  has_many :posts, dependent: :destroy 
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :set_post


	def create  
	  @comment = @post.comments.build(comment_params)
	  @comment.user_id = current_user.id
	 

	  if @comment.save
	    flash[:success] = "You commented the hell out of that post!"
	    redirect_to :back
	  else
	    flash[:alert] = "Check the comment form, something went horribly wrong."
	    render root_path
	  end
	end

		def destroy  
		  @comment = @post.comments.find(params[:id])

		  @comment.destroy
		  flash[:success] = "Comment deleted :("
		  redirect_to root_path
		end  

	private

	def comment_params  
	  params.require(:comment).permit(:image, :content)
	end

	def set_post  
	  @post = Post.find(params[:post_id])
	end  


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]
  before_action :owned_post, only: [:edit, :update, :destroy]
	def index
		@posts = Post.all
		@posts = Post.order("created_at desc")
	end

	  def new
	    @post = current_user.posts.build
	  end

	  def create
	    @post = current_user.posts.build(post_params)

	    if @post.save
	      flash[:success] = "Your post has been created!"
	      redirect_to posts_path
	    else
	      flash[:alert] = "Your new post couldn't be created!  Please check the form."
	      render :new
	    end
	  end

	def show  
	  @post = Post.find(params[:id])
	end  

	def edit  
	  @post = Post.find(params[:id])
	end  

	def update  
	  @post = Post.find(params[:id])
	  @post.update(post_params)
	  redirect_to(post_path(@post))
	end  

	def destroy  
	  @post = Post.find(params[:id])
	  @post.destroy
	  redirect_to posts_path
	end  

	private

	  def post_params
	    params.require(:post).permit(:image, :caption)
	  end

	  def set_post
	    @post = Post.find(params[:id])
	  end

		def owned_post  
		  unless current_user == @post.user
		    flash[:alert] = "That post doesn't belong to you!"
		    redirect_to root_path
		  end
		end  

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end

end  

app/helpers/application_helper.rb
module ApplicationHelper

	def alert_for(flash_type)  
	  { success: 'alert-success',
	    error: 'alert-danger',
	    alert: 'alert-warning',
	    notice: 'alert-info'
	  }[flash_type.to_sym] || flash_type.to_s
	end  
	
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
	<nav class="navbar navbar-default navbar-fixed-top">
  <div class="navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <div class="navbar-brand">
        <%= link_to image_tag("tnasty.png"), root_path, :alt => "tnasty" %>
      </div>

    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to "New Post", new_post_path %>
          </li>
          <li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path %>
          </li>
          <li>
            <%= link_to "Register", new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>tnastyapp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>



<body>

		<%= render 'layouts/navbar' %>


<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
<% end %>


<%= yield %>



</body>
</html>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-head">
      <div class="thumb-img"></div>
      <div class="user-name">
        <%= post.user.user_name %>
      </div>
    </div>
    <div class="image center-block">
      <% if post.image.exists? %>
      <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
      <% end %>
    </div>
    <div class="post-bottom">
      <div class="caption">
        <div class="user-name">
          <%= post.user.user_name %>
        </div>
        <%= link_to post.caption, post_path(post) %>
      </div>
      <% if post.comments %>
        <% post.comments.each do |comment| %>
          <div class="comment row">
              <div class="user-comment-name col-sm-2">
                <% if comment.user == current_user %>
                  <%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" } do %>
                    <span class="glyphicon glyphicon-remove delete-comment"></span>
                  <% end %>
                <% end %>


                <div class="user-name">
                  <%= comment.user.user_name %>
                </div>
              </div>
              <div class="col-sm-9">
            <% if comment.image.exists? %>
              <div class="image center-block">
                <%= link_to (image_tag comment.image.url(:medium), class:'img-responsive'), post_path(post) %>
              </div>
            <% end %>
                        <div class="comment-content">
              <%= comment.content %>
            </div>
          </div>
            


           
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="comment-like-form row">
      <div class="like-button col-xs-1">
        <span class="glyphicon glyphicon-heart-empty"></span>
      </div>
      
      <!--  <div class="add-comment col-xs-11">Add comment...</div> -->
        <div class="comment-wrapper">
        <div class="comment-form col-sm-12">
         
              <%= simple_form_for [post, post.comments.new] do |f| %>
                <div class="form-group">
                  <%= f.input :image %>
                </div>
                <div class="form-group">
                  <%= f.input :content, :label => "Add Comment", :as => :text %>
                </div>
                <div class="form-group text-center">
                  <%= f.button :submit, class: 'btn-success' %>
                </div>
              <% end %>
          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="text-center">
  <% if @post.image.exists? %>
  <%= image_tag @post.image.url(:medium) %>
  <% end %>
</div>
<div class="form-wrapper">
  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption, :as => :text %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>
<div class="text-center edit-links">
  <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
  |
    <%= link_to "cancel", posts_path %>
</div>

</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<div class="form-wrapper">
  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption, :as => :text %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<%= render 'post', post: @post %>

<% if @post.user.id == current_user.id %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_path %>
    |
    <%= link_to "Edit Post", edit_post_path(@post) %>
  </div>
<% else %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_path %>
  </div>
<% end %>